// deprecateds/vue3_vite/pagea/src/views/Home.vue
<script setup lang="ts">
import { NButton } from 'naive-ui'
import { useRouter } from 'vue-router'
const router = useRouter()
</script>

<template>
  <div class="flex-center h-screen">
    <n-button
      type="primary"
      size="large"
      @click="router.push('/chat')"
      class="animate-bounce hover:scale-110 transition-transform"
    >
      开始对话
    </n-button>
  </div>
</template>

// deprecateds/vite_react_ts/pageb/pages/Home.tsx
import { useNavigate } from 'react-router-dom'
import clsx from 'clsx'

export default function Home() {
  const nav = useNavigate()
  return (
    <div className="flex h-screen items-center justify-center">
      <button
        onClick={() => nav('/chat')}
        className={clsx(
          'rounded bg-blue-500 px-6 py-3 text-white shadow-lg',
          'hover:scale-110 transition-transform animate-bounce'
        )}
      >
        开始对话
      </button>
    </div>
  )
}
