// deprecateds/vite_react_ts/pageb/components/ChatInput.tsx
import { useState } from 'react'
import { useChatStore } from '@/stores/chat'

export default function ChatInput() {
  const [text, setText] = useState('')
  const addMessage = useChatStore(s => s.addMessage)

  const send = () => {
    if (!text.trim()) return
    addMessage({ role: 'user', content: text, type: 'text' })
    setText('')
    // TODO: 调本地 RAG API，异步 addMessage({ role:'assistant', ... })
  }

  return (
    <div className="border-t p-2 bg-white">
      <textarea
        rows={1}
        value={text}
        onChange={e => setText(e.target.value)}
        onKeyDown={e => {
          if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault()
            send()
          }
        }}
        placeholder="回车发送，Shift+Enter 换行"
        className="w-full resize-none rounded border p-2"
      />
    </div>
  )
}

// deprecateds/vue3_vite/pagea/src/ChatInput.vue
// ChatInput.vue（回车发送）
<script setup lang="ts">
import { ref } from 'vue'
import { useChatStore } from '@/stores/chat'

const chat = useChatStore()
const text = ref('')

const send = () => {
  if (!text.value.trim()) return
  chat.addMessage({ role: 'user', content: text.value, type: 'text' })
  text.value = ''
  // TODO: 调用本地 RAG 智能体，异步再把 assistant 消息 push
}
</script>

<template>
  <div class="p-3 bg-white border-t">
    <n-input
      v-model:value="text"
      type="textarea"
      :autosize="{ minRows: 1, maxRows: 4 }"
      placeholder="回车发送，Shift+Enter 换行"
      @keydown.enter.prevent="send"
    />
  </div>
</template>
