// deprecateds/vue3_vite/pagea/src/components/Message.vue
// components/Message.vue（消息组件）
<script setup lang="ts">
import type { Message as M } from '@/stores/chat'
defineProps<{ msg: M }>()
</script>

<template>
  <div class="mb-3">
    <div :class="msg.role === 'user' ? 'text-right' : ''">
      <div class="inline-block p-2 rounded bg-white max-w-md text-left">
        <div v-if="msg.type === 'image'"><img :src="msg.content" class="rounded" /></div>
        <div v-else>{{ msg.content }}</div>
        <div v-if="msg.refs?.length" class="text-xs text-gray-500 mt-1">
          引用：<span v-for="r in msg.refs" :key="r">{{ r }} </span>
        </div>
      </div>
    </div>
  </div>
</template>

// deprecateds/vite_react_ts/pageb/components/Message.tsx
import type { Message as M } from '@/stores/chat'

export default function Message({ msg }: { msg: M }) {
  const isUser = msg.role === 'user'
  return (
    <div className={`flex ${isUser ? 'justify-end' : 'justify-start'}`}>
      <div
        className="max-w-md rounded bg-white p-2 shadow"
        style={{ whiteSpace: 'pre-wrap' }}
      >
        {msg.type === 'image' ? (
          <img src={msg.content} alt="img" className="rounded" />
        ) : (
          <>{msg.content}</>
        )}
        {msg.refs && (
          <div className="mt-1 text-xs text-gray-500">
            引用：{msg.refs.join(', ')}
          </div>
        )}
      </div>
    </div>
  )
}
