// deprecateds/vue3_vite/pagea/src/components/SideBar.vue
// components/SideBar
<script setup lang="ts">
import { NButton, NCollapse, NCollapseItem } from 'naive-ui'
import { useChatStore, useLayoutStore } from '@/stores'
const chat = useChatStore()
const layout = useLayoutStore()
</script>

<template>
  <aside
    :class="[
      'bg-gray-100 transition-all flex flex-col',
      layout.sidebarCollapsed ? 'w-0 p-0 overflow-hidden' : 'w-64 p-3'
    ]"
  >
    <n-button @click="chat.newChat()" class="mb-2 w-full">新建对话</n-button>

    <n-collapse>
      <n-collapse-item title="今天" name="today">
        <div v-for="c in chat.groupedHistories.today" :key="c.id"
             @click="chat.activeId = c.id"
             class="cursor-pointer truncate p-1 hover:bg-blue-100 rounded"
        >{{ c.title }}</div>
      </n-collapse-item>
      <n-collapse-item title="7天内" name="week">
        <div v-for="c in chat.groupedHistories.week" :key="c.id"
             @click="chat.activeId = c.id"
             class="cursor-pointer truncate p-1 hover:bg-blue-100 rounded"
        >{{ c.title }}</div>
      </n-collapse-item>
      <n-collapse-item title="更早" name="earlier">
        <div v-for="c in chat.groupedHistories.earlier" :key="c.id"
             @click="chat.activeId = c.id"
             class="cursor-pointer truncate p-1 hover:bg-blue-100 rounded"
        >{{ c.title }}</div>
      </n-collapse-item>
    </n-collapse>

    <n-button @click="layout.toggle()" class="mt-auto">
      {{ layout.sidebarCollapsed ? '展开' : '收起' }}
    </n-button>
  </aside>
</template>

// deprecateds/vite_react_ts/pageb/components/SideBar.tsx
import { useChatStore, useLayoutStore } from '@/stores'
import { PlusIcon, ChevronDoubleLeftIcon } from '@heroicons/react/24/outline'

const groups = [
  { key: 'today', label: '今天' },
  { key: 'week', label: '7 天内' },
  { key: 'earlier', label: '更早' }
]

export default function SideBar() {
  const { collapsed, toggle } = useLayoutStore()
  const { newChat, setActive, groupedHistories } = useChatStore()

  return (
    <aside
      className={`bg-gray-100 transition-all flex flex-col overflow-hidden
        ${collapsed ? 'w-0' : 'w-64'} p-3 space-y-3`}
    >
      <button
        onClick={newChat}
        className="flex items-center gap-2 rounded bg-blue-600 px-3 py-2 text-sm text-white"
      >
        <PlusIcon className="h-4 w-4" /> 新建对话
      </button>

      {groups.map(g => (
        <div key={g.key}>
          <h4 className="font-semibold text-sm mb-1">{g.label}</h4>
          {groupedHistories[g.key as keyof typeof groupedHistories].map(c => (
            <div
              key={c.id}
              onClick={() => setActive(c.id)}
              className="truncate p-1 rounded hover:bg-blue-100 cursor-pointer"
            >
              {c.title}
            </div>
          ))}
        </div>
      ))}

      <button
        onClick={toggle}
        className="mt-auto flex items-center gap-1 text-sm text-gray-600"
      >
        <ChevronDoubleLeftIcon className="h-4 w-4" />
        {collapsed ? '展开' : '收起'}
      </button>
    </aside>
  )
}
